LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE        := MiuiCamera
LOCAL_SRC_FILES     := MiuiCamera/MiuiCamera.apk
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_CERTIFICATE   := PRESIGNED
LOCAL_MODULE_PATH  := $(TARGET_OUT_APPS_PRIVILEGED)
LOCAL_OVERRIDES_PACKAGES := ParanoidCamera Camera2
include $(BUILD_PREBUILT)
